# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: fpweb
builds:
  - env:
      - CGO_ENABLED=0
    id: "fpweb"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "v1.0.0"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
